=== vladik7go/WebProject/source/staff.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/staff"
	xmlns:tns="http://www.example.com/staff" elementFormDefault="qualified">
	<element name="staff">
		<complexType>
			<sequence>
				<element ref="tns:employee" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<element name="employee" type="tns:employeeType" abstract="true" />
	<element name="manager" type="tns:managerType"
		substitutionGroup="tns:employee" />
	<element name="operator" type="tns:operatorType"
		substitutionGroup="tns:employee" />

	<complexType name="employeeType" abstract="true">
		<sequence>

			<element name="firstName" type="string" />
			<element name="id" type="tns:idType" />
			<element name="secondName" type="string" />
		</sequence>
		<attribute name="city" use="optional" default="Minsk">
			<simpleType>
				<restriction base="string">
					<enumeration value="Minsk"></enumeration>
					<enumeration value="Berlin"></enumeration>
					<enumeration value="Bonn"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="managerType">
		<complexContent>
			<extension base="tns:employeeType">

				<sequence>
					<element name="bonus" type="int" />
				</sequence>
				<attribute name="pass" type="tns:password" use="required" />

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="password">
		<restriction base="ID">
			<pattern value="([a-zA-Z])[a-zA-Z0-9]{7,12}"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="idType">
		<restriction base="ID">
			<pattern value="[a-zA-Z].*" />
		</restriction>
	</simpleType>

	<complexType name="operatorType">
		<complexContent>
			<extension base="tns:employeeType">
				<sequence>
					<element name="numberOfTools" type="int" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
</schema>

=== vladik7go/WebProject/source/staff.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:staff xmlns:tns="http://www.example.com/staff"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.com/staff staff.xsd ">

	<tns:manager pass="aasd123123123" city="Berlin">
		<tns:firstName>Ivan</tns:firstName>
		<tns:id>n001</tns:id>
		<tns:secondName>Filimonau</tns:secondName>
		<tns:bonus>1500</tns:bonus>
	</tns:manager>

	<tns:manager pass="d123123444" city="Minsk">
		<tns:firstName>Sarah</tns:firstName>
		<tns:id>n002</tns:id>
		<tns:secondName>Connor</tns:secondName>
		<tns:bonus>3500</tns:bonus>
	</tns:manager>

	<tns:operator city="Minsk">
		<tns:firstName>John</tns:firstName>
		<tns:id>n003</tns:id>
		<tns:secondName>Connor</tns:secondName>
		<tns:numberOfTools>3</tns:numberOfTools>
	</tns:operator>



</tns:staff>
